### ISSUE TITLE
Checksum for RC_2024-03.zst_blocks

### ISSUE THREAD

**Issue by rEnr3n** [ArthurHeitmann/arctic_shift#11]
I have downladed `RC_2024-03.zst_blocks` twice now and I got this checksum both times.

`c58412dd23cce1bba902992a48bd889fda5b2a78a38eb75108745fb8960d0e03`

Could you verify it again?

**Comment by ArthurHeitmann** [comment]
Yes you are right, thank you. I accidentally copied the checksum from RS_2023-04.zst_blocks instead. The hashes_sha256.txt file had the correct one. I've updated it in the github release now.
