### ISSUE TITLE
"Slow down a little" Error when using API

### ISSUE THREAD

**Issue by felixwoestmann** [ArthurHeitmann/arctic_shift#12]
Hello, 
I have been trying to use the provided api to aggregate comments but always receive this error, which does not seem to be documented.

Am I doing something wrong? :)

`curl https://arctic-shift.photon-reddit.com/api/comments/search/aggregate?aggregate=author&subreddit=conspiracy&after=2023-01-01&limit=10`

Response:
`{"data":null,"error":"Slow down a little"}`

**Comment by ArthurHeitmann** [comment]
Hi, r/conspiracy is quite a big subreddit and unfortunately I currently don't have the computing resources to process large amounts of data in a couple of seconds. So there's a hard limit for how long a query can run. If it takes too long, you get that error message.

There are a couple of options here:
1. Reduce the time frame until it works
2. Download data by subreddit (through dumps or the API), and then process it yourself
3. If it's for a research project or similar, I can manually start a query, without time limitations, and then give you the result, once it's done

**Comment by felixwoestmann** [comment]
Thanks! i downloaded the data and wrote a script myself to obtain the results. :)
