### ISSUE TITLE
zstd decompress error: Frame requires too much memory for decoding

### ISSUE THREAD

**Issue by hanyidaxia** [ArthurHeitmann/arctic_shift#19]
I am using the zstandard decompress to deal with the .zst file, the zstandard streaming decompress works well for files in 2024 and 2023,  but when I randomly picked a file in 2010, this error keeps jumping out no matter how small the chunk size I set.

**Comment by ArthurHeitmann** [comment]
Can you say which files exactly you are having this problem with?

**Comment by hanyidaxia** [comment]
Hi Arthur,

Solved the problem by using your decoding function, thanks a lot!
