### ISSUE TITLE
How to open JSONL files downloaded directly from the website

### ISSUE THREAD

**Issue by traviss64** [ArthurHeitmann/arctic_shift#20]
As the title says

I tried a few tools including MS VS Code but the JSONL files show error. Is there any way to open them?

**Comment by ArthurHeitmann** [comment]
In [this line](https://github.com/ArthurHeitmann/arctic_shift/blob/679c4e23d402bca259faaa387d24efb8a66ebca5/scripts/fileStreams.py#L75) change `.json` to `.jsonl`. Then it should work. I should correct that soon.

**Comment by ArthurHeitmann** [comment]
For clarification, the .jsonl file extension means, that one line of text in the file is one json object. One json object is one post or comment, depending on the file you are reading.

What you do with that json object depends on what your actual goal is. Examples of fields you can use:

```python
username = row["author"]
subreddit = row["subreddit"]
# comments only
commentText = row["body"]
# posts only
postTitle = row["title"]
postText = row["selftext"]
postUrl = row["url"]
```

In general I would recommend to just take a look at the data you are dealing with and see what kind of fields there are. Open a jsonl file in a text editor, copy one line, format the json object (ide or online tool) and understand what you are dealing with.
