### ISSUE TITLE
Total Karma API Vs. Reddit Profiles

### ISSUE THREAD

**Issue by noahholtgraves** [ArthurHeitmann/arctic_shift#25]
Hello @ArthurHeitmann, thank you so much for taking on the monstrous task of archiving Reddit data for research. I am working with your API for a data journalism-based digital PR project and had a question about the total karma for Redditors pulled with the API. 

I noticed a fairly large difference between post/comment karma from the API and what is displayed on Redditor's profiles and was hoping you could clear up the discrepancy if you have time. 

My assumption is that the total karma provided in the API includes karma from archived and deleted posts and comments, and I want to ensure that the monthly data dumps are not duplicating karma for Redditors. Is my assumption correct, and are entries de-duplicated when new information is added?

Thank you so much for your time in advance, and I hope to hear from you soon!

**Comment by ArthurHeitmann** [comment]
First, the karma displayed on users profiles on reddit isn't just a sum of all individual comment and post scores. Highly upvoted items are weighted less and downvoted content either doesn't count or only a little. 

My /api/users/search ending just sums all scores in the database. There are no duplicates. 

All released archives after 2023-03 I can guarantee that they are duplicate free. The older ones released by pushshift I'm not 100% sure. It's possible that some older files have 0.01% duplicates.
