### ISSUE TITLE
[QUESTION] Datetime of each comment

### ISSUE THREAD

**Issue by DavidHerel** [ArthurHeitmann/arctic_shift#3]
Hi,

I have a question regarding each dump e.g. January 2022. It means that all the comments are guaranteed they are from January 2022 or does it mean everything which was scraped during this month is here?

Thanks for the response :)

**Comment by ArthurHeitmann** [comment]
Yes, the archives are organized by the creation date `created_utc`. So January 2022 will only have data from that month.
