### ISSUE TITLE
Removal requests

### ISSUE THREAD

**Issue by JodanJodan** [ArthurHeitmann/arctic_shift#4]
Could you implement a user removal system similar to [Pushshift's](https://old.reddit.com/r/pushshift/comments/pat409/online_removal_request_form_for_removal_requests/) and [PullPush's](https://removals.pullpush.io/), for general privacy / CCPA / GDPR reasons? This request is primarily concerning [the Photon API](https://github.com/ArthurHeitmann/arctic_shift/tree/master/api) for parity w/ Pushshift since they didn't remove from subsequent data dumps, but it would be nice for future data dumps to exclude the content as well. This could be done through a manual form (e.g. Pushshift/Pullpush) or automatically through an OAuth gateway using [the "identity" scope](https://old.reddit.com/dev/api/oauth/) for verification.

**Comment by ArthurHeitmann** [comment]
Yes that's definitely something that I'll add soon. I have already functionality to filter users from data dumps and API requests. Only thing missing is a form. The automatic authentication through reddit sounds like a good idea.

**Comment by ArthurHeitmann** [comment]
I didn't have much time yet. So for now I've added a google forms link to the readme.

**Comment by ArthurHeitmann** [comment]
Final update (after a long time): I'll keep things the way they are now (google forms). The number of removal requests is relatively small and often enough the accounts in question are deleted. So authentication doesn't work there.
