### ISSUE TITLE
Searching comments by body text without an author or post or link id?

### ISSUE THREAD

**Issue by ntripet** [ArthurHeitmann/arctic_shift#8]
Right now we can only search comments by a specified user or in a specified post. Is it possible to allow Reddit-wide searching of comments and posts?

**Comment by ArthurHeitmann** [comment]
Unfortunately not. With my current setup such a query could take hours. It's just too much data to search through. So I'm only offering what I know I can support. There is another independent platform called [pullpush.io](https://pullpush.io), which might work better for this.
