### ISSUE TITLE
Donation Link?

### ISSUE THREAD

**Issue by richardklafter** [ArthurHeitmann/arctic_shift#9]
Just found this project and am excited to see this data feed didn't die with Pushshift! I am downloading all the data I didn't have from 2023 now. 

I used to donate to Pushshift. You have an ETH or BTC or whatever I can donate to?

**Comment by richardklafter** [comment]
Also, a nit, on future releases can you include something like https://github.com/ArthurHeitmann/arctic_shift/blob/master/file_content_explanations.md or a README in the torrent itself?

**Comment by ArthurHeitmann** [comment]
Thank you for wanting to support me. On my [profile page](https://github.com/ArthurHeitmann) are links to paypal and buy me a coffe. Or if that doesn't work, I can arrange something else.

So far the torrents have been distributed by [u/Watchful1](reddit.com/user/Watchful1). With the later torrents there should be at least a link back to this repo.

**Comment by richardklafter** [comment]
Sent and thank you for keeping this data available!

**Comment by ArthurHeitmann** [comment]
Thanks for the support :)
